### ISSUE TITLE
Add to Chrome Web Store

### ISSUE THREAD

**Issue by jahir** [jaens/no-pdf-download#4]
Could you add this to the Chrome store, just like the original extension (which seems quite abandonded)? It loads and runs fine on Chrome.

OTOH, Chrome complains about manifest version 2, for which the support will allegedly be removed in 2024, so it might make more sense to create a fork and update to manifest v3 (not sure if it will still compatible).

**Comment by jaens** [comment]
I am not sure if a port to manifest v3 is even possible, given the security model changes which AFAIK made programmatically changing requests with JS impossible, in particular the `webRequestBlocking` permission which this extension uses (also disabling adblockers such as uBlock Origin).

See [Google’s Manifest V3 Still Hurts Privacy, Security, and Innovation | Electronic Frontier Foundation](https://www.eff.org/deeplinks/2021/12/googles-manifest-v3-still-hurts-privacy-security-innovation) if you like drama.

A very nerfed and buggy version might be possible via `declarativeNetRequest`. Thank Google. At this point I have given up on using Chrome due to their stance on advanced extensions.

They could have replaced `webRequestBlocking` with something that fulfilled most of their objectives while also keeping most of its power (as used by legitimate extensions), but I believe the incredibly simplistic and underpowered design of `declarativeNetRequest` and the kneecapping of ad blockers etc. was intentional. The extension developer community has yelled at them for 2 years now, the end result: basically token changes with no actual substance, Google is hoping to slowly "boil the frog" I guess.

**Comment by jaens** [comment]
Note that `webRequestBlocking` is still available for policy-installed extensions, so if you are a developer/advanced user, that's still one possible avenue.

Chrome Extension Store is out of the question, obviously, though.

I'll probably make a policy/developer-only MV3 version once they remove MV2 fully.

**Comment by jahir** [comment]
ok, thanks.
I guess most things of no-pdf-download could be done in a framework like `declarativeNetRequest`, but the header modifications are quite limited and the conditions only allow basic stuff.

**Comment by jaens** [comment]
Indeed, as I meant by "buggy", `declarativeNetRequest` would not support things like keeping the attachment filename in case you do want to save the PDF after viewing it, not breaking apps which use hidden PDF iframes for printing etc. etc. It's just very dumb.
